refactor fix/backend
vantage-ola/track-now pull request #10
Opened 2023-12-20 11:33 UTC by Dozie2001

Closes #9. This refactor offers a cleaner  approach for Models

2023-12-20 12:23 UTC, Dozie2001 commented on DEPENDENCIES.txt
>  pymongo==4.6.1
You didn't add this to the DEPENDENCIES

2023-12-20 12:33 UTC, vantage-ola requested changes
good, just need to do the same for track_id

2023-12-20 12:33 UTC, vantage-ola commented on backend/models.py
>              'track_id': self.track_id,
you would have to do for track_id also, so dict_track['id']...

2023-12-20 16:15 UTC, vantage-ola requested changes

2023-12-20 16:15 UTC, vantage-ola commented on backend/models.py
> +            'track_id': self.track_id
*self.Track.id , just this change and its fine....good work bro..

2023-12-21 07:37 UTC, Dozie2001 reviewed
I have fixed the mistakes I made

2023-12-21 07:40 UTC, vantage-ola approved these changes
good one bro

2023-12-21 07:40 UTC, merged